NAME="common"
DESC="
A common configuration of the suckless terminal
"
FLAGS="linux"
PATCHES="
0001-copyurl.patch
0002-blinking_cursor.patch
0003-newterm.patch
0004-onedark.patch
0005-clickurl.patch
0006-clipboard.patch
0007-glyph.patch
0008-zsh.patch
"
